
format = """
[](green)\
$os\
$username\
[](bg:yellow fg:green)\
$git_status\
$git_branch\
[](fg:yellow bg:green)\
$directory\
[](fg:green bg:crust)\
$c\
$rust\
$python\
$conda\
[](fg:crust bg:lavender)\
$time\
[ ](fg:lavender)\
$cmd_duration\
$line_break\
$character"""

palette = 'k3ff'

[os]
disabled = false
style = "bg:red fg:crust"

[os.symbols]
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Fedora = "󰣛"
CachyOS = " 󰣨 "
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"

[username]
show_always = false
style_user = "bg:red fg:crust"
style_root = "bg:red fg:crust"
format = '[ $user]($style)'

[directory]
style = "bg:green fg:yellow"
format = "[ $path ]( $style)"
truncation_length = 5
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "doc "
"Downloads" = "dl "
"Music" = "musi "
"Pictures" = "pic "
"Developer" = "dev "
"Musik" = "sndfx"
"Bilder" = "pix"
"Skrivbort" = "snickarbänk"

[git_branch]
symbol = "gif"
style = "bg:crust"
format = '[[ $branch ](fg:green bg:yellow)]($style)'

[git_status]
style = "bg:yellow"
format = '[[($all_status$ahead_behind )](fg:crust bg:peach)]($style)'

[nodejs]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[c]
symbol = " "
style = "bg:crust"
format = '[[.c ](fg:green bg:crust)]($style)'

[rust]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[golang]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[php]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[java]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[kotlin]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[haskell]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[python]
symbol = "!reefland! "
style = "bg:crust"
format = '[[ $symbol(\(#$virtualenv\)) ](fg:green bg:crust)]($style)'

[docker_context]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $context) ](bg:crust fg:sapphire)]($style)'

[conda]
symbol = "  "
style = "fg:crust bg:sapphire"
format = '[$symbol$environment ]($style)'
ignore_base = false

[time]
disabled = false
time_format = "%R"
style = "bg:lavender"
format = '[[ $time ](fg:crust bg:lavender)]($style)'

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[❯](bold fg:green)'
error_symbol = '[!poo](bold fg:text)'
vimcmd_symbol = '[❮](bold fg:green)'
vimcmd_replace_one_symbol = '[❮](bold fg:lavender)'
vimcmd_replace_symbol = '[❮](bold fg:lavender)'
vimcmd_visual_symbol = '[❮](bold fg:yellow)'

[cmd_duration]
show_milliseconds = true
format = " in $duration "
style = "bg:lavender"
disabled = true
show_notifications = true
min_time_to_notify = 45000

[palettes.k3ff]
rosewater = "#31302F"
flamingo = "#1D2021"
pink = "#131620"
mauve = "#131620"
red = "#3C465B"
maroon = "#7184C1"
peach = "#7184C1"
yellow = "#131620"
green = "#3C465B"
teal = "#6D82B8"
sky = "#6D82B8"
sapphire = "#131620"
blue = "#6D82B8"
lavender = "#3C465B"
text = "#6D82B8"
surface0 = "#ccd0da"
surface1 = "#bcc0cc"
subtext1 = "#171A1A"
subtext0 = "#6D82B8"
overlay2 = "#3C465B"
overlay1 = "#5F5852"
overlay0 = "#8B8279"
surface2 = "#928374"
base = "#6D82B8"
mantle = "#1d2021"
crust = "#131620"

